### ISSUE TITLE
Error reading file at file:///Applications/Fuse.app/./../../Contents/.mono_root

### ISSUE THREAD

**Issue by knatten** [fusetools/Fuse.SublimePlugin#13]
I am using a checked out version of the Sublime Package on OS X. I'm at c57527f in `~/Library/Application Support/Sublime Text 3/Packages/Fuse`, working directory clean.

Got this error message:

```
Unexpected fatal error! Please report this to us.
2015-11-24 09:06:20.758 fuse[3424:81836] Error reading file at file:///Applications/Fuse.app/./../../Contents/.mono_root
The file doesn’t exist.
```

**Comment by knatten** [comment]
Here's a bit of logging:
```
2015-11-24 09:05:32,868 [3420] INFO Finished configuring logging for Fuse
2015-11-24 09:05:32,868 [3420] INFO Loading plugin
2015-11-24 09:05:32,870 [3420] INFO Plugin loaded successfully
2015-11-24 09:05:33,739 [3420] INFO Calling subprocess '['fuse', 'daemon', '-b']'
2015-11-24 09:05:33,780 [3420] INFO Sending hello request
2015-11-24 09:05:33,790 [3420] INFO Got Hello response
2015-11-24 09:05:33,791 [3420] ERROR Traceback (most recent call last):
  File "/Users/knatten/Library/Application Support/Sublime Text 3/Packages/Fuse/fuse.py", line 218, in tryConnectThread
    self.interop.connect()
  File "/Users/knatten/Library/Application Support/Sublime Text 3/Packages/Fuse/interop.py", line 32, in connect
    self.on_connect()
  File "/Users/knatten/Library/Application Support/Sublime Text 3/Packages/Fuse/fuse.py", line 186, in sendHello
    "EventFilter": ""
  File "/Users/knatten/Library/Application Support/Sublime Text 3/Packages/Fuse/msg_parser.py", line 54, in sendRequest
    if (res["response"] != None and len(res["response"].errors) > 0):
TypeError: object of type 'NoneType' has no len()

2015-11-24 09:06:20,724 [3420] INFO Starting preview for ['/Users/knatten/code/shoppinglist/app/MainView.ux']
2015-11-24 09:06:20,725 [3420] INFO Opening subprocess ['fuse', 'preview', '--target=Local', '--name=Sublime_Text_3', '/Users/knatten/code/shoppinglist/app/MainView.ux']
```

**Comment by knatten** [comment]
Happened again last night on my home iMac. Fuse 0.9.2.5183 (official release), normal (not from git) Sublime plugin. Tried deleting and re-installing the plugin, which didn't help.

Then it happened now on my work computer with Fuse 0.9.2.5183 and checked out Sublime plugin. Deleted that and re-installed, didn't help.

**Comment by ericraio** [comment]
+1 this was happening for me

**Comment by knatten** [comment]
@ericraio We still have a bit of testing left, as this is somewhat hard to reproduce, but we believe this is a bug in Fuse that has been fixed in the upcoming release due to be released this week.

A workaround that seems to fix it is to close Sublime, delete `~/Library/Application\ Support/Sublime\ Text\ 3/Installed\ Packages/Fuse*`, and then do `fuse install sublime-plugin`.

**Comment by knatten** [comment]
Fixed in https://github.com/fusetools/Fuse/issues/1679
